### ISSUE TITLE
AzurLane adapter base url is wrong

### ISSUE THREAD

**Issue by solclearsky** [KaikyuLotus/moe-moe-secretary#25]
base url should be https://azurlane.koumakan.jp/wiki/ instead of without /wiki/
and space should be replaced with underscore

![image](https://user-images.githubusercontent.com/84186928/215857702-c19efa55-10a1-43db-9336-6929b94e92ba.png)
![a](https://user-images.githubusercontent.com/84186928/215857742-6f01db21-8ab3-4043-af27-5c7827e4355d.png)

**Comment by ale183** [comment]
This issue (and #19) should be resolved in the latest release
